const LANGS = {
    en: {
        flag: '🇬🇧', name: 'English',
        login_title: 'Rigid Logic ERP',
        login_subtitle: 'Sign in to your account',
        username_label: 'Username',
        username_placeholder: 'Enter your username',
        password_label: 'Password',
        password_placeholder: 'Enter your password',
        login_btn: 'Sign In',
        logging_in: 'Signing in...',
        footer: '© 2026 Rigid Logic. All rights reserved.',
        err_empty: 'Please fill in all fields.',
        err_invalid: 'Invalid username or password.',
        err_too_many: 'Too many attempts. Please wait.',
        err_generic: 'Login failed. Please try again.',
        nav_home: 'Dashboard',
        nav_calendar: 'Calendar',
        nav_tasks: 'Tasks',
        nav_messages: 'Messages',
        nav_users: 'Users',
        nav_approvals: 'Approvals',
        nav_main_menu: 'Main Menu',
        nav_management: 'Management',
        logout: 'Logout',
        role_admin: 'Admin',
        role_user: 'User',
        stat_total_tasks: 'Total Tasks',
        stat_pending: 'Pending',
        stat_in_progress: 'In Progress',
        stat_completed: 'Completed',
        stat_pending_approvals: 'Pending Approvals',
        recent_activity: 'Recent Activity',
        no_activity: 'No activity yet',
        load_failed: 'Failed to load',
        calendar_add_event: '+ Add Event',
        new_event: 'New Event',
        event_title: 'Title',
        event_title_placeholder: 'Event title',
        event_date: 'Date',
        event_description: 'Description',
        event_desc_placeholder: 'Description (optional)',
        event_approval_note: 'Events will appear on the calendar after admin approval.',
        event_save: 'Save',
        event_detail: 'Event Detail',
        event_status: 'Status',
        event_added_by: 'Added by:',
        event_update: 'Update',
        event_delete: 'Delete',
        event_delete_confirm: 'Are you sure you want to delete this event?',
        event_update_fail: 'Failed to update event.',
        event_delete_fail: 'Failed to delete event.',
        event_add_fail: 'Failed to add event.',
        status_approved: 'Approved',
        status_pending: 'Pending',
        status_rejected: 'Rejected',
        tasks_title: 'Tasks',
        new_task: '+ New Task',
        task_all: 'All',
        task_pending: 'Pending',
        task_in_progress: 'In Progress',
        task_completed: 'Completed',
        task_assigned_to: 'Assigned to:',
        task_assigned_by: 'Assigned by:',
        task_date: 'Date:',
        task_not_found: 'No tasks found',
        task_loading: 'Loading...',
        task_load_fail: 'Failed to load tasks',
        task_create: 'Create Task',
        task_title_label: 'Title',
        task_title_placeholder: 'Task title',
        task_desc_label: 'Description',
        task_desc_placeholder: 'Description',
        task_assignee: 'Assign To',
        task_assignee_select: 'Select',
        task_due_date: 'Due Date',
        task_create_btn: 'Create',
        task_create_fail: 'Failed to create task.',
        task_update_fail: 'Update failed.',
        task_delete_confirm: 'Are you sure you want to delete this task?',
        task_delete_fail: 'Failed to delete task.',
        task_admin_only: 'Only admins can create tasks.',
        task_status_pending: 'Pending',
        task_status_in_progress: 'In Progress',
        task_status_completed: 'Completed',
        messages_title: 'Chats',
        msg_placeholder: 'Type your message...',
        msg_no_users: 'No other users yet',
        msg_select_user: 'Select a user to chat',
        msg_no_messages: 'No messages yet',
        msg_send_fail: 'Failed to send message.',
        users_title: 'Users',
        new_user: '+ New User',
        user_col_user: 'User',
        user_col_username: 'Username',
        user_col_role: 'Role',
        user_col_date: 'Reg. Date',
        user_col_actions: 'Actions',
        user_edit: 'Edit',
        user_delete: 'Delete',
        create_user_title: 'New User',
        user_fullname: 'Full Name',
        user_fullname_placeholder: 'Full name',
        user_username_placeholder: 'Username for login',
        user_password_placeholder: 'Min 6 characters',
        user_role: 'Role',
        user_create_btn: 'Create',
        user_creating: 'Creating...',
        user_created: 'successfully created!',
        user_exists: 'This username already exists.',
        user_weak_pass: 'Password must be at least 6 characters.',
        edit_user_title: 'Edit User',
        user_username_locked: 'Username cannot be changed',
        user_new_pass: 'New Password (leave empty to keep current)',
        user_new_pass_placeholder: 'New password (optional)',
        user_save: 'Save',
        user_saving: 'Saving...',
        user_save_partial: 'Info updated but password change may have failed.',
        user_delete_confirm: 'Are you sure you want to delete this user?\n\nThis action cannot be undone.',
        user_deleted: 'deleted.',
        user_delete_fail: 'Failed to delete user:',
        approvals_title: 'Pending Events',
        approval_date: 'Date:',
        approval_added_by: 'Added by:',
        approval_approve: 'Approve',
        approval_reject: 'Reject',
        approval_none: 'No pending events',
        approval_fail: 'Action failed.',
    },
    de: {
        flag: '🇩🇪', name: 'Deutsch',
        login_title: 'Rigid Logic ERP',
        login_subtitle: 'Melden Sie sich bei Ihrem Konto an',
        username_label: 'Benutzername',
        username_placeholder: 'Benutzername eingeben',
        password_label: 'Passwort',
        password_placeholder: 'Passwort eingeben',
        login_btn: 'Anmelden',
        logging_in: 'Anmeldung...',
        footer: '© 2026 Rigid Logic. Alle Rechte vorbehalten.',
        err_empty: 'Bitte füllen Sie alle Felder aus.',
        err_invalid: 'Ungültiger Benutzername oder Passwort.',
        err_too_many: 'Zu viele Versuche. Bitte warten.',
        err_generic: 'Anmeldung fehlgeschlagen. Bitte erneut versuchen.',
        nav_home: 'Startseite',
        nav_calendar: 'Kalender',
        nav_tasks: 'Aufgaben',
        nav_messages: 'Nachrichten',
        nav_users: 'Benutzer',
        nav_approvals: 'Genehmigungen',
        nav_main_menu: 'Hauptmenü',
        nav_management: 'Verwaltung',
        logout: 'Abmelden',
        role_admin: 'Administrator',
        role_user: 'Benutzer',
        stat_total_tasks: 'Gesamtaufgaben',
        stat_pending: 'Ausstehend',
        stat_in_progress: 'In Bearbeitung',
        stat_completed: 'Abgeschlossen',
        stat_pending_approvals: 'Ausstehende Genehmigungen',
        recent_activity: 'Letzte Aktivitäten',
        no_activity: 'Noch keine Aktivitäten',
        load_failed: 'Laden fehlgeschlagen',
        calendar_add_event: '+ Ereignis hinzufügen',
        new_event: 'Neues Ereignis',
        event_title: 'Titel',
        event_title_placeholder: 'Ereignistitel',
        event_date: 'Datum',
        event_description: 'Beschreibung',
        event_desc_placeholder: 'Beschreibung (optional)',
        event_approval_note: 'Ereignisse erscheinen nach Admin-Genehmigung im Kalender.',
        event_save: 'Speichern',
        event_detail: 'Ereignisdetails',
        event_status: 'Status',
        event_added_by: 'Hinzugefügt von:',
        event_update: 'Aktualisieren',
        event_delete: 'Löschen',
        event_delete_confirm: 'Möchten Sie dieses Ereignis wirklich löschen?',
        event_update_fail: 'Ereignis konnte nicht aktualisiert werden.',
        event_delete_fail: 'Ereignis konnte nicht gelöscht werden.',
        event_add_fail: 'Ereignis konnte nicht hinzugefügt werden.',
        status_approved: 'Genehmigt',
        status_pending: 'Ausstehend',
        status_rejected: 'Abgelehnt',
        tasks_title: 'Aufgaben',
        new_task: '+ Neue Aufgabe',
        task_all: 'Alle',
        task_pending: 'Ausstehend',
        task_in_progress: 'In Bearbeitung',
        task_completed: 'Abgeschlossen',
        task_assigned_to: 'Zugewiesen an:',
        task_assigned_by: 'Zugewiesen von:',
        task_date: 'Datum:',
        task_not_found: 'Keine Aufgaben gefunden',
        task_loading: 'Laden...',
        task_load_fail: 'Aufgaben konnten nicht geladen werden',
        task_create: 'Aufgabe erstellen',
        task_title_label: 'Titel',
        task_title_placeholder: 'Aufgabentitel',
        task_desc_label: 'Beschreibung',
        task_desc_placeholder: 'Beschreibung',
        task_assignee: 'Zuweisen an',
        task_assignee_select: 'Auswählen',
        task_due_date: 'Fälligkeitsdatum',
        task_create_btn: 'Erstellen',
        task_create_fail: 'Aufgabe konnte nicht erstellt werden.',
        task_update_fail: 'Aktualisierung fehlgeschlagen.',
        task_delete_confirm: 'Möchten Sie diese Aufgabe wirklich löschen?',
        task_delete_fail: 'Aufgabe konnte nicht gelöscht werden.',
        task_admin_only: 'Nur Administratoren können Aufgaben erstellen.',
        task_status_pending: 'Ausstehend',
        task_status_in_progress: 'In Bearbeitung',
        task_status_completed: 'Abgeschlossen',
        messages_title: 'Chats',
        msg_placeholder: 'Nachricht eingeben...',
        msg_no_users: 'Noch keine anderen Benutzer',
        msg_select_user: 'Benutzer zum Chatten auswählen',
        msg_no_messages: 'Noch keine Nachrichten',
        msg_send_fail: 'Nachricht konnte nicht gesendet werden.',
        users_title: 'Benutzer',
        new_user: '+ Neuer Benutzer',
        user_col_user: 'Benutzer',
        user_col_username: 'Benutzername',
        user_col_role: 'Rolle',
        user_col_date: 'Reg.-Datum',
        user_col_actions: 'Aktionen',
        user_edit: 'Bearbeiten',
        user_delete: 'Löschen',
        create_user_title: 'Neuer Benutzer',
        user_fullname: 'Vollständiger Name',
        user_fullname_placeholder: 'Vollständiger Name',
        user_username_placeholder: 'Benutzername für die Anmeldung',
        user_password_placeholder: 'Mindestens 6 Zeichen',
        user_role: 'Rolle',
        user_create_btn: 'Erstellen',
        user_creating: 'Erstellen...',
        user_created: 'erfolgreich erstellt!',
        user_exists: 'Dieser Benutzername existiert bereits.',
        user_weak_pass: 'Passwort muss mindestens 6 Zeichen haben.',
        edit_user_title: 'Benutzer bearbeiten',
        user_username_locked: 'Benutzername kann nicht geändert werden',
        user_new_pass: 'Neues Passwort (leer lassen für aktuelles)',
        user_new_pass_placeholder: 'Neues Passwort (optional)',
        user_save: 'Speichern',
        user_saving: 'Speichern...',
        user_save_partial: 'Infos aktualisiert, aber Passwortänderung ist möglicherweise fehlgeschlagen.',
        user_delete_confirm: 'Möchten Sie diesen Benutzer wirklich löschen?\n\nDiese Aktion kann nicht rückgängig gemacht werden.',
        user_deleted: 'gelöscht.',
        user_delete_fail: 'Benutzer konnte nicht gelöscht werden:',
        approvals_title: 'Ausstehende Ereignisse',
        approval_date: 'Datum:',
        approval_added_by: 'Hinzugefügt von:',
        approval_approve: 'Genehmigen',
        approval_reject: 'Ablehnen',
        approval_none: 'Keine ausstehenden Ereignisse',
        approval_fail: 'Aktion fehlgeschlagen.',
    },
    ru: {
        flag: '🇷🇺', name: 'Русский',
        login_title: 'Rigid Logic ERP',
        login_subtitle: 'Войдите в свой аккаунт',
        username_label: 'Имя пользователя',
        username_placeholder: 'Введите имя пользователя',
        password_label: 'Пароль',
        password_placeholder: 'Введите пароль',
        login_btn: 'Войти',
        logging_in: 'Вход...',
        footer: '© 2026 Rigid Logic. Все права защищены.',
        err_empty: 'Пожалуйста, заполните все поля.',
        err_invalid: 'Неверное имя пользователя или пароль.',
        err_too_many: 'Слишком много попыток. Подождите.',
        err_generic: 'Ошибка входа. Попробуйте снова.',
        nav_home: 'Главная',
        nav_calendar: 'Календарь',
        nav_tasks: 'Задачи',
        nav_messages: 'Сообщения',
        nav_users: 'Пользователи',
        nav_approvals: 'Одобрения',
        nav_main_menu: 'Главное меню',
        nav_management: 'Управление',
        logout: 'Выйти',
        role_admin: 'Администратор',
        role_user: 'Пользователь',
        stat_total_tasks: 'Всего задач',
        stat_pending: 'Ожидающие',
        stat_in_progress: 'В процессе',
        stat_completed: 'Завершённые',
        stat_pending_approvals: 'Ожидают одобрения',
        recent_activity: 'Последняя активность',
        no_activity: 'Активности пока нет',
        load_failed: 'Не удалось загрузить',
        calendar_add_event: '+ Добавить событие',
        new_event: 'Новое событие',
        event_title: 'Название',
        event_title_placeholder: 'Название события',
        event_date: 'Дата',
        event_description: 'Описание',
        event_desc_placeholder: 'Описание (необязательно)',
        event_approval_note: 'События появятся в календаре после одобрения администратора.',
        event_save: 'Сохранить',
        event_detail: 'Детали события',
        event_status: 'Статус',
        event_added_by: 'Добавил:',
        event_update: 'Обновить',
        event_delete: 'Удалить',
        event_delete_confirm: 'Вы уверены, что хотите удалить это событие?',
        event_update_fail: 'Не удалось обновить событие.',
        event_delete_fail: 'Не удалось удалить событие.',
        event_add_fail: 'Не удалось добавить событие.',
        status_approved: 'Одобрено',
        status_pending: 'Ожидает',
        status_rejected: 'Отклонено',
        tasks_title: 'Задачи',
        new_task: '+ Новая задача',
        task_all: 'Все',
        task_pending: 'Ожидающие',
        task_in_progress: 'В процессе',
        task_completed: 'Завершённые',
        task_assigned_to: 'Назначена:',
        task_assigned_by: 'Назначил:',
        task_date: 'Дата:',
        task_not_found: 'Задачи не найдены',
        task_loading: 'Загрузка...',
        task_load_fail: 'Не удалось загрузить задачи',
        task_create: 'Создать задачу',
        task_title_label: 'Название',
        task_title_placeholder: 'Название задачи',
        task_desc_label: 'Описание',
        task_desc_placeholder: 'Описание',
        task_assignee: 'Назначить',
        task_assignee_select: 'Выберите',
        task_due_date: 'Срок',
        task_create_btn: 'Создать',
        task_create_fail: 'Не удалось создать задачу.',
        task_update_fail: 'Ошибка обновления.',
        task_delete_confirm: 'Вы уверены, что хотите удалить эту задачу?',
        task_delete_fail: 'Не удалось удалить задачу.',
        task_admin_only: 'Только администраторы могут создавать задачи.',
        task_status_pending: 'Ожидает',
        task_status_in_progress: 'В процессе',
        task_status_completed: 'Завершена',
        messages_title: 'Чаты',
        msg_placeholder: 'Введите сообщение...',
        msg_no_users: 'Других пользователей пока нет',
        msg_select_user: 'Выберите пользователя для чата',
        msg_no_messages: 'Сообщений пока нет',
        msg_send_fail: 'Не удалось отправить сообщение.',
        users_title: 'Пользователи',
        new_user: '+ Новый пользователь',
        user_col_user: 'Пользователь',
        user_col_username: 'Логин',
        user_col_role: 'Роль',
        user_col_date: 'Дата рег.',
        user_col_actions: 'Действия',
        user_edit: 'Изменить',
        user_delete: 'Удалить',
        create_user_title: 'Новый пользователь',
        user_fullname: 'Полное имя',
        user_fullname_placeholder: 'Полное имя',
        user_username_placeholder: 'Логин для входа',
        user_password_placeholder: 'Минимум 6 символов',
        user_role: 'Роль',
        user_create_btn: 'Создать',
        user_creating: 'Создание...',
        user_created: 'успешно создан!',
        user_exists: 'Этот логин уже существует.',
        user_weak_pass: 'Пароль должен содержать минимум 6 символов.',
        edit_user_title: 'Редактировать пользователя',
        user_username_locked: 'Логин нельзя изменить',
        user_new_pass: 'Новый пароль (оставьте пустым для текущего)',
        user_new_pass_placeholder: 'Новый пароль (необязательно)',
        user_save: 'Сохранить',
        user_saving: 'Сохранение...',
        user_save_partial: 'Данные обновлены, но смена пароля могла не пройти.',
        user_delete_confirm: 'Вы уверены, что хотите удалить этого пользователя?\n\nЭто действие необратимо.',
        user_deleted: 'удалён.',
        user_delete_fail: 'Не удалось удалить пользователя:',
        approvals_title: 'Ожидающие события',
        approval_date: 'Дата:',
        approval_added_by: 'Добавил:',
        approval_approve: 'Одобрить',
        approval_reject: 'Отклонить',
        approval_none: 'Нет ожидающих событий',
        approval_fail: 'Действие не удалось.',
    },
    tr: {
        flag: '🇹🇷', name: 'Türkçe',
        login_title: 'Rigid Logic ERP',
        login_subtitle: 'Hesabınıza giriş yapın',
        username_label: 'Kullanıcı Adı',
        username_placeholder: 'Kullanıcı adınızı girin',
        password_label: 'Şifre',
        password_placeholder: 'Şifrenizi girin',
        login_btn: 'Giriş Yap',
        logging_in: 'Giriş yapılıyor...',
        footer: '© 2026 Rigid Logic. Tüm hakları saklıdır.',
        err_empty: 'Lütfen tüm alanları doldurun.',
        err_invalid: 'Kullanıcı adı veya şifre hatalı.',
        err_too_many: 'Çok fazla deneme. Lütfen bekleyin.',
        err_generic: 'Giriş yapılamadı. Lütfen tekrar deneyin.',
        nav_home: 'Ana Sayfa',
        nav_calendar: 'Takvim',
        nav_tasks: 'Görevler',
        nav_messages: 'Mesajlar',
        nav_users: 'Kullanıcılar',
        nav_approvals: 'Onaylar',
        nav_main_menu: 'Ana Menü',
        nav_management: 'Yönetim',
        logout: 'Çıkış',
        role_admin: 'Yönetici',
        role_user: 'Kullanıcı',
        stat_total_tasks: 'Toplam Görev',
        stat_pending: 'Bekleyen',
        stat_in_progress: 'Devam Eden',
        stat_completed: 'Tamamlanan',
        stat_pending_approvals: 'Onay Bekleyen',
        recent_activity: 'Son Aktiviteler',
        no_activity: 'Henüz aktivite yok',
        load_failed: 'Yüklenemedi',
        calendar_add_event: '+ Etkinlik Ekle',
        new_event: 'Yeni Etkinlik',
        event_title: 'Başlık',
        event_title_placeholder: 'Etkinlik başlığı',
        event_date: 'Tarih',
        event_description: 'Açıklama',
        event_desc_placeholder: 'Açıklama (opsiyonel)',
        event_approval_note: 'Etkinlikler admin onayından sonra takvimde görünecektir.',
        event_save: 'Kaydet',
        event_detail: 'Etkinlik Detayı',
        event_status: 'Durum',
        event_added_by: 'Ekleyen:',
        event_update: 'Güncelle',
        event_delete: 'Sil',
        event_delete_confirm: 'Bu etkinliği silmek istediğinize emin misiniz?',
        event_update_fail: 'Etkinlik güncellenemedi.',
        event_delete_fail: 'Etkinlik silinemedi.',
        event_add_fail: 'Etkinlik eklenemedi.',
        status_approved: 'Onaylandı',
        status_pending: 'Onay Bekliyor',
        status_rejected: 'Reddedildi',
        tasks_title: 'Görevler',
        new_task: '+ Yeni Görev',
        task_all: 'Tümü',
        task_pending: 'Bekleyen',
        task_in_progress: 'Devam Eden',
        task_completed: 'Tamamlanan',
        task_assigned_to: 'Atanan:',
        task_assigned_by: 'Atayan:',
        task_date: 'Tarih:',
        task_not_found: 'Görev bulunamadı',
        task_loading: 'Yükleniyor...',
        task_load_fail: 'Görevler yüklenemedi',
        task_create: 'Görev Oluştur',
        task_title_label: 'Başlık',
        task_title_placeholder: 'Görev başlığı',
        task_desc_label: 'Açıklama',
        task_desc_placeholder: 'Açıklama',
        task_assignee: 'Atanacak Kişi',
        task_assignee_select: 'Seçiniz',
        task_due_date: 'Bitiş Tarihi',
        task_create_btn: 'Oluştur',
        task_create_fail: 'Görev oluşturulamadı.',
        task_update_fail: 'Güncelleme başarısız.',
        task_delete_confirm: 'Bu görevi silmek istediğinize emin misiniz?',
        task_delete_fail: 'Görev silinemedi.',
        task_admin_only: 'Sadece yöneticiler görev oluşturabilir.',
        task_status_pending: 'Bekleyen',
        task_status_in_progress: 'Devam Eden',
        task_status_completed: 'Tamamlandı',
        messages_title: 'Sohbetler',
        msg_placeholder: 'Mesajınızı yazın...',
        msg_no_users: 'Henüz başka kullanıcı yok',
        msg_select_user: 'Mesajlaşmak için bir kullanıcı seçin',
        msg_no_messages: 'Henüz mesaj yok',
        msg_send_fail: 'Mesaj gönderilemedi.',
        users_title: 'Kullanıcılar',
        new_user: '+ Yeni Kullanıcı',
        user_col_user: 'Kullanıcı',
        user_col_username: 'Kullanıcı Adı',
        user_col_role: 'Rol',
        user_col_date: 'Kayıt Tarihi',
        user_col_actions: 'İşlemler',
        user_edit: 'Düzenle',
        user_delete: 'Sil',
        create_user_title: 'Yeni Kullanıcı',
        user_fullname: 'Ad Soyad',
        user_fullname_placeholder: 'Adı ve soyadı',
        user_username_placeholder: 'Giriş için kullanılacak',
        user_password_placeholder: 'En az 6 karakter',
        user_role: 'Rol',
        user_create_btn: 'Oluştur',
        user_creating: 'Oluşturuluyor...',
        user_created: 'başarıyla oluşturuldu!',
        user_exists: 'Bu kullanıcı adı zaten mevcut.',
        user_weak_pass: 'Şifre en az 6 karakter olmalı.',
        edit_user_title: 'Kullanıcı Düzenle',
        user_username_locked: 'Kullanıcı adı değiştirilemez',
        user_new_pass: 'Yeni Şifre (boş bırakırsanız değişmez)',
        user_new_pass_placeholder: 'Yeni şifre (opsiyonel)',
        user_save: 'Kaydet',
        user_saving: 'Kaydediliyor...',
        user_save_partial: 'Bilgiler güncellendi ancak şifre değiştirilememiş olabilir.',
        user_delete_confirm: 'Bu kullanıcıyı silmek istediğinize emin misiniz?\n\nBu işlem geri alınamaz.',
        user_deleted: 'silindi.',
        user_delete_fail: 'Kullanıcı silinemedi:',
        approvals_title: 'Onay Bekleyen Etkinlikler',
        approval_date: 'Tarih:',
        approval_added_by: 'Ekleyen:',
        approval_approve: 'Onayla',
        approval_reject: 'Reddet',
        approval_none: 'Onay bekleyen etkinlik yok',
        approval_fail: 'İşlem başarısız.',
    }
};

let currentLang = localStorage.getItem('erp_lang') || 'en';

function T(key) {
    return LANGS[currentLang]?.[key] || LANGS['en'][key] || key;
}

function setLang(lang) {
    currentLang = lang;
    localStorage.setItem('erp_lang', lang);
}

function getLang() {
    return currentLang;
}
